# sheldon configuration file
#
# Modify this file directly or use one of the following `sheldon` commands
# which are provided to assist in editing the config file:
#
# `sheldon add` to add a new plugin to the config file
# `sheldon edit` to open up the config file in the default editor
# `sheldon remove` to remove a plugin from the config file
#
# See https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.dracula]
github = "dracula/zsh"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"

