# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 3000

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$nodejs\
$python\
$ruby\
$direnv\
$env_var\
$mise\
$custom\
$sudo\
$line_break\
$jobs\
$os\
$container\
$shell\
$character
"""

right_format = '$cmd_duration $status'

continuation_prompt = '[â†ª](white) '

palette = 'gradoo'

[palettes.gradoo]
# TODO

[character]
error_symbol = '[îª‡](white)' # nf-cod-error
success_symbol = '[â¯](white)'
vimcmd_symbol = '[â®](bold green)'
vimcmd_replace_symbol = '[â®](bold purple)'
vimcmd_visual_symbol = '[â®](bold yellow)'

[cmd_duration]
format = '[$duration]($style)'
style = 'bold yellow'

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
style = 'bold cyan'
home_symbol = 'â™¥' # nf-oct-heart
read_only = ' ó°©' # nf-md-hand_front_right
read_only_style = 'bold red'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
repo_root_style = 'underline white'
truncation_length = 7
truncation_symbol = 'â€¦/'

[docker_context]
disabled = true

[git_branch]
style = 'bold magenta'
symbol = 'ï˜' # nf-oct-git_branch
format = 'on [$branch(:$remote_branch)]($style) '
truncation_symbol = 'â€¦'

[git_commit]
commit_hash_length = 7
format = '[ï— $hash$tag]($style) ' #nf-oct-git_commit
tag_disabled = false
tag_symbol = ' ï’ ' # nf-oct-tag

[git_state]
bisect = 'BISECTING'
cherry_pick = '[ğŸ’ PICKING](bold red)'
merge = 'ï™ MERGING' # nf-oct-git_merge
rebase = 'ï‡ REBASING' # nf-oct-git_pull_request
revert = 'ï“› REVERTING' # nf-oct-git_merge_queue
format = '[\($state( $progress_current of $progress_total)\)]($style)'

[git_status]
format = '([$all_status( $ahead_behind)]($style)) '
ahead = 'î«¼ğŸ¢${count}' # nf-cod-git_commit
behind = 'î«¼ğŸ¢ƒ${count}' # nf-cod-git_commit
conflicted = 'î¿‹' # nf-fa-not_equal
deleted = 'â•'
diverged = 'î«¼ğŸ¢ğŸ¢ƒ' # nf-cod-git_commit
modified = 'ğŸ—¯ï¸'
renamed = 'ï‘š' # nf-oct-diff_renamed
staged = '[+$count](green)'
stashed = 'îª¥ ' # nf-cod-bookmark
style = 'white'
untracked = 'â”'
up_to_date = 'î®¤' # nf-cod-pass

[hostname]
disabled = false
format = '[$ssh_symbol](bold blue)[$hostname]($style) '
ssh_only = false
ssh_symbol = 'SSH:'
style = 'yellow'

[mise]
disabled = false
format = '[$symbol $health]($style) '
healthy_symbol = 'ó±‹' # nf-md-lightning_bolt
style = 'bold purple'
symbol = 'mise'
unhealthy_symbol = 'ï¡' # nf-oct-alert

[nodejs]
format = '[$symbol $version]($style) '
symbol = 'Node'
version_format = '${raw}'

[python]
format = '[$symbol $version]($style) '
pyenv_version_name = true
symbol = 'Python'
version_format = '${raw}'

[ruby]
format = '[$symbol $version]($style) '
symbol = 'Ruby'
version_format = '${raw}'

[shell]
disabled = false
format = '[$indicator]($style)'
style = 'white'
bash_indicator = 'îš‘' # nf-seti-shell
fish_indicator = 'ğŸŸ'
nu_indicator = '' # default indicator
unknown_indicator = 'ï„¨' # nf-fa-question
zsh_indicator = 'ïŠ•' # nf-fa-percent

[sudo]
disabled = false
format = '[as $symbol]($style)'
style = 'bold green'
symbol = 'ïŒ‚' # nf-dev-apple

[username]
disabled = true
format = '[$user]($style)'
show_always = true
style_root = 'red'
style_user = 'white'
