# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 3000

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$nodejs\
$python\
$ruby\
$direnv\
$env_var\
$mise\
$custom\
$sudo\
$line_break\
$jobs\
$os\
$container\
$shell\
$character
"""

right_format = "$cmd_duration $status"

continuation_prompt = '[â†ª](white) '

palette = 'gradoo'

[palettes.gradoo]
# TODO

[character]
error_symbol = '[â¯](white)'
success_symbol = '[â¯](white)'
vimcmd_symbol = '[â®](bold green)'
vimcmd_replace_symbol = '[â®](bold purple)'
vimcmd_visual_symbol = '[â®](bold yellow)'

[cmd_duration]
format = '[$duration]($style)'
style = 'bold yellow'

[directory]
format = '[$path]($style)[$read_only]($read_only_style) '
style = 'bold cyan'
read_only = ''
read_only_style = 'bold red'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
repo_root_style = 'underline white'
truncation_length = 8
truncation_symbol = 'â€¦/'

[docker_context]
disabled = true

[git_branch]
style = 'bold magenta'
symbol = ''
truncation_symbol = ''

[git_commit]
format = '[$hash \[$tag\]]($style) '
tag_symbol = 'ï’'

[git_state]
bisect = 'BISECTING'
cherry_pick = '[ğŸ’](bold red)'
merge = 'MERGING'
rebase = 'REBASING'
revert = 'REVERTING'
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
format = '([$all_status$ahead_behind]($style) )'
ahead = 'â†‘${count}'
behind = 'â†“${count}'
conflicted = 'â‰ '
deleted = 'âœ˜'
diverged = 'ğŸ¡™'
modified = 'â•'
renamed = 'ğŸ –'
staged = '[+$count](green)'
stashed = 'ï‚—'
untracked = '?'
up_to_date = 'ï®'

[hostname]
disabled = false
format = '[$ssh_symbol](bold blue)[$hostname]($style) '
ssh_only = false
ssh_symbol = 'SSH:'
style = 'yellow'

[mise]
disabled = false
format = '[$symbol $health]($style) '
healthy_symbol = 'ó±‹'
style = 'bold purple'
symbol = 'mise'
unhealthy_symbol = 'ï¡'

[nodejs]
format = '[$symbol $version]($style) '
symbol = 'Node'
version_format = '${raw}'

[python]
format = '[$symbol $version]($style) '
pyenv_version_name = true
symbol = 'Python'
version_format = '${raw}'

[ruby]
format = '[$symbol $version]($style) '
symbol = 'Ruby'
version_format = '${raw}'

[shell]
disabled = false
format = "[$indicator]($style)"
style = "white"
bash_indicator = "\\$"
fish_indicator = "ğŸŸ"
nu_indicator = "" # use default
unknown_indicator = "?"
zsh_indicator = "%"

[sudo]
disabled = false
format = '[as $symbol]($style)'
style = 'bold green'
symbol = 'ïŒ‚'

[username]
disabled = true
format = '[$user]($style)'
show_always = true
style_root = 'red'
style_user = 'white'
