[settings]
activate_aggressive = true
env_file = ".env"
experimental = true
paranoid = false

[settings.python]
uv_venv_auto = true

[settings.ruby]
verbose_install = true

[settings.status]
missing_tools = "always"
show_env = false
show_tools = false

[tools]
# allow mise to verify tools automatically
cosign = "latest"
slsa-verifier = "latest"

# usage-spec support for tasks
usage = "latest"

node = "latest"
python = "latest"
ruby = "latest"

"npm:npm-check-updates" = "latest"
"npm:tinpig" = "latest"
